[profile.default]
solc = "0.8.15"
ffi = true
gas_reports = ["*"]
out = "out"
optimizer_runs = 1000000

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = "single"